language: node_js
sudo: false
node_js:
    - stable
install:
    - npm install
    - export PATH="node_modules/.bin:$PATH"
    - psc --version
    - pulp --version
    - bower install
script:
    - pulp build
      #- pulp test
